---
- name: Configure the EC2
  hosts: all
  become: yes
  tasks:
    - name: Create devops group
      ansible.builtin.group:
        name: devops
        state: present

    - name: Copy config file to /opt/
      ansible.builtin.copy:
        src: ./config.txt
        dest: /opt/config.txt
        owner: root
        group: devops
        mode: '0644'

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: latest

    - name: Ensure PostgreSQL service is running
      service:
        name: postgresql
        state: started
        enabled: true

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: true
